### ISSUE TITLE
update cpptraj manual

### ISSUE THREAD

**Issue by fwaibl** [Amber-MD/amber-md.github.io#5]
Dear Dan (@drroe),

I noticed that the cpptraj online manual is not up-to-date. It says that it was updated on 2020-07-21, and at least none of the recent GIST updates (PME, or the more recent ones) are incorporated.

Would it be possible to update the page? Is the page automatically generated from the cpptraj manual, or are the changes copied manually? In the latter case, I could offer some help with copying in the new documentation.

Best regards,
Franz

**Comment by drroe** [comment]
Oh boy - I honestly forgot this site was a thing.

So the PDF of the manual is generated automatically by Jenkins [here](https://jenkins.jasonswails.com/job/amber-github/job/cpptraj/job/master/lastSuccessfulBuild/artifact/doc/CpptrajManual.pdf), but the HTML is not. I'm sure there's some clever way to get the HTML generated and pushed here, but I'm not sure how to do that. For the time being I'll have to do this manually - I'll try to get to it tonight or tomorrow. Thanks for the reminder.

**Comment by drroe** [comment]
Should be addressed by #6, but it doesn't seem to have percolated out to the web yet.

**Comment by hainm** [comment]
@drroe  If you have a single site to maintain the docs, you can direct this website https://amber-md.github.io/cpptraj/ to it.

**Comment by drroe** [comment]
Seems like it's up to date now.
